replace DataSource's self.log
After adding the 'log' element to the DataSource class, pickling would
fail with 
  TypeError: can't pickle file objects

Instead of having the object with a log reference, use one from 
'DataSource.log' and have that set by cloudinit