tools/net-convert: fix argument order for render_network_state
We're calling Renderer.render_network_state() with incorrect args.

% PYTHONPATH=`pwd` ./tools/net-convert.py \
   --network-data=simple-v2.yaml --kind=yaml \
   --output-kind netplan --directory ./target

Traceback (most recent call last):
  File "./tools/net-convert.py", line 82, in <module>
    main()
  File "./tools/net-convert.py", line 78, in main
    r.render_network_state(ns, target=args.directory)
TypeError: render_network_state() got multiple values for argument 'target'

The method signature requires passing <target dir>, <network_state>.
This patch fixes the call order.

LP: #1685944