tox: avoid tox testenv subsvars for xenial support (#684)
Xenial tox 2.3.1 still suffers from
    https://github.com/tox-dev/tox/issues/208.

As a result we cannot use testenv substvars if we want to support running
tox on xenial systems.

Drop the {[testenv:integration-tests]*} substitutions to avoid tracebacks
when running `tox -e xenial-dev` which has the signature:

   "No support for the %s substitution type" % sub_type)
   tox.ConfigError: ConfigError: No support for the posargs substitution
   type