tests: expect intermittent warning accessing Azure IMDS. Avoid client.destroy
Avoid client.destroy within the cloud_session.launch context manager
as it already performs cloud.destroy on context exit which calls
instance.destroy. This avoids the following error seen by pycloudlib
on Azure instances:

  <pycloudlib.azure.instance.AzureInstance object at ....

  @property
  def id(self):
      """Return instance id."""
      return self._instance["vm"].id
               ^^^^^^^^^^^^^^^^^^^^
      TypeError: 'NoneType' object is not subscriptable

Additionally, some Azure instance launches encounter intemittent
warning reaching IMDS on first attempt. Avoid failing integration
tests when encountering a single warning about IMDS access.

If multiple retries are required to reach Azure IMDS, treat this as
an error.