tests/helpers: raise TypeError when subp called with no args
This more accurately mirrors normal behaviour:

```py
>>> from cloudinit.util import subp
>>> subp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: subp() missing 1 required positional argument: 'args'
```