fix: Make `make fmt` pass by fixing mypy errors in 'crypt' module stubs (#6507)
The `make fmt` command was failing due to `mypy` errors:

    $ make fmt
    ...
    Cannot find implementation or library stub for module named "crypt"
    cloudinit/distros/netbsd.py:15: error: Cannot find implementation or
      library stub for module named "crypt"
    cloudinit/sources/DataSourceAzure.py:53: error: Cannot find
      implementation or library stub for module named "crypt"

Resolve this by adding `type: ignore` comments to instructs `mypy` to
skip type checking for this specific import, allowing the format check
to pass without suppressing other type-checking.

Detected on latest Debian unstable running `python3-mypy-extensions`
version 1.1.0-1.