config/cc_resizefs: fix do_resize arguments (#2106)
Daily PPA builds were crashing due to
refactor: stop passing log instances to cc_* handlers (#2016).

When dropping the logger argument, the tuple became a list which
then gets expanded in the call to do_resize() and crashes.

```
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 257, in _run_modules
    run_name, mod.handle, func_args, freq=freq
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 67, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 172, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py", line 309, in handle
    args=(resize_cmd),
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2722, in log_time
    ret = func(*args, **kwargs)

TypeError: do_resize() takes 1 positional argument but 2 were given
```

Restore args as a tuple.

Signed-off-by: Chris Patterson <cpatterson@microsoft.com>