get_interfaces: don't exclude Open vSwitch bridge/bond members
If an OVS bridge was used as the only/primary interface, the 'init'
stage failed with the following error, leaving the system with a broken
SSH setup:

Cloud-init v. 20.3-2-g371b392c-0ubuntu1~20.04.1 running 'init' at Fri, 09 Oct 2020 11:00:25 +0000. Up 18.61 seconds.
ci-info: +++++++++++++++++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++++++++++++++++
ci-info: +------------+-------+------------------------------+---------------+--------+-------------------+
ci-info: |   Device   |   Up  |           Address            |      Mask     | Scope  |     Hw-Address    |
ci-info: +------------+-------+------------------------------+---------------+--------+-------------------+
ci-info: |    ens4    |  True |              .               |       .       |   .    | 52:54:00:d9:08:1c |
ci-info: |     lo     |  True |          127.0.0.1           |   255.0.0.0   |  host  |         .         |
ci-info: |     lo     |  True |           ::1/128            |       .       |  host  |         .         |
ci-info: |   ovs-br   |  True |         172.16.99.24         | 255.255.255.0 | global | 8a:9f:21:67:58:40 |
ci-info: |   ovs-br   |  True | fe80::889f:21ff:fe67:5840/64 |       .       |  link  | 8a:9f:21:67:58:40 |
ci-info: | ovs-system | False |              .               |       .       |   .    | 1e:01:ef:a1:74:63 |
ci-info: +------------+-------+------------------------------+---------------+--------+-------------------+
ci-info: +++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: | Route | Destination |   Gateway   |    Genmask    | Interface | Flags |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: |   0   |   0.0.0.0   | 172.16.99.1 |    0.0.0.0    |   ovs-br  |   UG  |
ci-info: |   1   | 172.16.99.0 |   0.0.0.0   | 255.255.255.0 |   ovs-br  |   U   |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   1   |  fe80::/64  |    ::   |   ovs-br  |   U   |
ci-info: |   3   |    local    |    ::   |   ovs-br  |   U   |
ci-info: |   4   |   ff00::/8  |    ::   |   ovs-br  |   U   |
ci-info: |   5   |   ff00::/8  |    ::   |    ens4   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
2020-10-09 11:00:26,374 - networking.py[WARNING]: Not all expected physical devices present: {'52:54:00:d9:08:1c'}
2020-10-09 11:00:26,383 - util.py[WARNING]: failed stage init
failed run of stage init
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 362, in main_init
    init.apply_network_config(bring_up=bool(mode != sources.DSMODE_LOCAL))
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 699, in apply_network_config
    self.distro.networking.wait_for_physdevs(netcfg)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/networking.py", line 172, in wait_for_physdevs
    raise RuntimeError(msg)
RuntimeError: Not all expected physical devices present: {'52:54:00:d9:08:1c'}
------------------------------------------------------------