cc_ssh: handle race between cloud-init and sshd-keygen
It looks like that at least in AWS RHEL 9 images there is
a race between cloud-init and sshd-keygen.
In particular, they both create /etc/ssh/ssh_host_*key*
at first boot, causing sometimes warning in cloud-init:

cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key']
Exit code: 1
Reason: -
Stdout: Generating public/private rsa key pair.
        /etc/ssh/ssh_host_rsa_key already exists.
        Overwrite (y/n)?
Stderr:

What happens is:
1) cloud-init checks if /etc/ssh/ssh_host_rsa_key exist
2) it does not exist, so it continues the logic in cc_ssh line 234
3) sshd-keygen in the meanwhile creates /etc/ssh/ssh_host_rsa_key
4) cloud-init issues
   'ssh-keygen -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key',
   failing

Masking the service with `systemctl mask sshd-keygen.target` fixes
the bug, but it is not the right solution.

The solution proposed here is to just analyze the error and
avoid throwing a warning if the file has been created in the meanwhile.

Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>